### ISSUE TITLE
Package 'setuptools' requires a different Python: 3.5.2 not in '>=3.6'

### ISSUE THREAD

**Issue by TopCoder2K** [askforalfred/alfred#111]
I'm trying to setup Alfred using [docker](https://github.com/askforalfred/alfred#docker-setup). Steps to reproduce:
 ```
 git clone https://github.com/askforalfred/alfred.git alfred
 export ALFRED_ROOT=$(pwd)/alfred
 cd $ALFRED_ROOT
 python scripts/docker_build.py 
```
The last command fails with
```
ERROR: Package 'setuptools' requires a different Python: 3.5.2 not in '>=3.6'
WARNING: You are using pip version 19.3.1; however, version 20.3.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip install -U setuptools' returned a non-zero code: 1
```

**Comment by TopCoder2K** [comment]
Would replacing `pip install --upgrade pip==19.3.1` with `pip install --upgrade pip==20.3.4` in the Dockerfile be a good solution for this?
At least the image was built successfully :)

**Comment by TopCoder2K** [comment]
Maybe I should open another issue but as I'm using pip=20.3.4 now, I'll post it here. 
After building the image I entered the following commands:
```
python scripts/docker_run.py --headless
tmux new -s startx
sudo nvidia-xconfig -a --use-display-device=None --virtual=1280x1024
sudo python ~/alfred/scripts/startx.py 0
```
And `sudo python ~/alfred/scripts/startx.py 0` fails with
```
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file
```
Why is this?..

**Comment by TopCoder2K** [comment]
@MohitShridhar, thank you for responding quickly!

> Have you tried startx.py 1 or >1?
Yes, I tried `startx.py 1` and `startx.py 2`, the error remains.

> You might have install extra packages depending on your hardware setup.
Hmm, interesting... Have you encountered any specific cases?

**Comment by MohitShridhar** [comment]
Actually, I am not sure because the default docker setup works on my machine. 

Maybe this might help: https://askubuntu.com/questions/1213538/ee-no-screens-found-when-startx ?

**Comment by TopCoder2K** [comment]
> Maybe this might help: https://askubuntu.com/questions/1213538/ee-no-screens-found-when-startx ?

Thank you for the link! Yeah, I've come across this, that's why I mentioned installing the modules that Xorg is trying to load. And I'll try to do it, but first I want to ask what is the output of  `sudo nvidia-xconfig -a --use-display-device=None --virtual=1280x1024` on your machine? 
I have this, and it's strange:
```
pchelintsev@neurosymbolic-panov3:~$ sudo nvidia-xconfig -a --use-display-device=None --virtual=1280x1024
[sudo] password for pchelintsev: 

WARNING: Unable to locate/open X configuration file.

Package xorg-server was not found in the pkg-config search path.
Perhaps you should add the directory containing `xorg-server.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xorg-server' found
New X configuration file written to '/etc/X11/xorg.conf'
```

It was mentioned [here](https://github.com/allenai/ai2thor/issues/886#issuecomment-917117154) that "It will complain if you have not had an Xorg config file" but "No package 'xorg-server' found" looks more like an error than a complaint.

**Comment by TopCoder2K** [comment]
I also decided to try setting up Alfred on a local computer with a physical display.
When I ran `sudo python3 scripts/docker_build.py`, I got:
```
Step 8/28 : RUN useradd -ms /bin/bash $USER_NAME
 ---> Running in 8c2872dcd725
useradd: user 'root' already exists
The command '/bin/sh -c useradd -ms /bin/bash $USER_NAME' returned a non-zero code: 9
```
So, I just commented the line in the Dockerfile (it seems that the problem has occurred because I have only the root user on my computer). And I also changed `pip==19.3.1` to `pip==20.3.4`. After this the image was built successfully. 

Then I tried to run the docker container. I got
```
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
Executed with code  32000
non-network local connections being removed from access control list
```
but solved it with proper [nvidia-container](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker) installation. After this I ran `source /home/root/alfred_env/bin/activate`, `cd /home/$ALFRED_ROOT` and `python scripts/check_thor.py`. The latter produced:
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Found path: /root/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64
Mono path[0] = '/root/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Managed'
Mono config path = '/root/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Mono/etc'
Preloaded 'ScreenSelector.so'
Display 0 'HP 24m 24"': 1920x1080 (primary device).
Logging to /root/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor/Player.log
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/root/alfred_env/lib/python3.5/site-packages/ai2thor/controller.py", line 697, in _start_unity_thread
    raise Exception("command: %s exited with %s" % (command, returncode))
Exception: command: ['/root/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64', '-screen-fullscreen', '0', '-screen-quality', '7', '-screen-width', '300', '-screen-height', '300'] exited with 1
```
which I haven't been able to handle yet. I saw https://github.com/askforalfred/alfred/issues/49 but since I don't use `startx.py` and I have `libGL error`, the discussions there are not really relevant, are they?

**Comment by TopCoder2K** [comment]
@MohitShridhar, I've updated the previous comment. Do you have any ideas why OpenGL isn't found inside docker?

**Comment by MohitShridhar** [comment]
@TopCoder2K, this looks like good progress. If you are seeing
```
(300, 300, 3)
Everything works!!!
```
that means it's good to go. Try evaluating a pre-trained model. It should work, I think.

And thanks for the Docker fixes. I'll look into these when I get some time.

**Comment by TopCoder2K** [comment]
@MohitShridhar, I tried to run evaluation but got `AttributeError: 'Namespace' object has no attribute 'use_templated_goals'`. It seems that it's not related to the changes I committed.

Steps to reproduce:

1. Run an ALFRED docker container (I used the image with OpenGL: `python scripts/docker_run.py --image svyatoslav-alfred-gl --container alfred-gl`)
2. `source ~/alfred_env/bin/activate`
3. `cd $ALFRED_ROOT`
4. `python models/eval/eval_seq2seq.py --model_path data/checkpoints/seq2seq_pm_chkpt/model\:seq2seq_im_mask\,name\:base30_pm010_sg010_01/best_seen.pth --eval_split valid_seen --data data/json_feat_2.1.0 --model models.model.seq2seq_im_mask --gpu --num_threads 1 --preprocess` (I downloaded the pretrained model and also added `--preprocess` flag and set `--num_threads 1` as noted [here](https://github.com/askforalfred/alfred/tree/master/models#task-evaluation)).

The result is:
```
{'tests_seen': 1533,
 'tests_unseen': 1529,
 'train': 21023,
 'valid_seen': 820,
 'valid_unseen': 821}
Loading:  data/checkpoints/seq2seq_pm_chkpt/model:seq2seq_im_mask,name:base30_pm010_sg010_01/best_seen.pth

Preprocessing dataset and saving to pp folders ... This is will take a while. Do this once as required:
Preprocessing valid_seen
  0% (0 of 820) |                                                                                                                                                   | Elapsed Time: 0:00:00 ETA:  --:--:--Traceback (most recent call last):
  File "models/eval/eval_seq2seq.py", line 55, in <module>
    eval = EvalTask(args, manager)
  File "/home/svyatoslav/alfred/models/eval/eval.py", line 45, in __init__
    dataset.preprocess_splits(self.splits)
  File "/home/svyatoslav/alfred/data/preprocess.py", line 67, in preprocess_splits
    use_templated_goals = self.args.use_templated_goals and train_mode # templated goals are not available for the test set
AttributeError: 'Namespace' object has no attribute 'use_templated_goals'
100% (820 of 820) |#################################################################################################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
```

Why is this?

**Comment by MohitShridhar** [comment]
@TopCoder2K, as noted by the comment`# templated goals are not available for the test set`, templated goals are not available for the test set. The ALFRED challenge involves grounding human-annotated goals. But you are free to use templated goals during training time for augmentation etc.

**Comment by TopCoder2K** [comment]
@MohitShridhar, does this also apply to the `valid_seen` which I'm using? I didn't use test set above.
If templated goals are not available for the valid split, then how should I run evaluation? (https://github.com/askforalfred/alfred/tree/master/models#task-evaluation)

**Comment by MohitShridhar** [comment]
@TopCoder2K, yes. See this for an extended discussion: https://github.com/askforalfred/alfred/issues/71#issuecomment-807887118

**Comment by TopCoder2K** [comment]
@MohitShridhar, should ["Note: If you are training and evaluating on different machines or if you just downloaded a checkpoint, you need to run eval with --preprocess once with the appropriate dataset path. Also, after a fresh-install, run with --num_threads 1 to allow the script to download the THOR binary"](https://github.com/askforalfred/alfred/tree/master/models#task-evaluation) be fixed then? It's impossible to run evaluation with `--preprocess` flag.

**Comment by gautierdag** [comment]
@TopCoder2K Did you ever manage to run Alfred on a headless server? 

I've been trying to get `ai2thor==2.1.0` running a SLURM node on which I don't have root privileges.

Xorg is out of the question because I don't have the privileges, but I have been able to use `xvfb-run`, though this crashes the UnityEngine somewhere.

The Unity error (in the `Player.log`): 
```
SocketException: The socket has been shut down
  at System.Net.Sockets.Socket.Send (System.Byte[] buf) [0x00000] in <filename unknown>:0
  at AgentManager+<EmitFrame>c__Iterator3.MoveNext () [0x00000] in <filename unknown>:0
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0

(Filename:  Line: -1)
```

I haven't tried Docker yet, but would appreciate pointers if you have a working setup for a headless node or any recommendations. 

Also, apologies for hijacking this old issue.

**Comment by TopCoder2K** [comment]
@gautierdag, I'm really sorry for my late reply. I've had tough weeks, I'm usually faster at answering... I hope you solved the problem or at least had a nice time :)

> Did you ever manage to run Alfred on a headless server?

Yes, I did! Sorry, I haven't worked with SLURM yet, I've set up ALFRED on an ordinary server to which I connect via ssh. 

> The Unity error (in the Player.log):

Hmm, do not remember having the same error and using `xvfb-run`. At least in my current setup it is not used.

> but would appreciate pointers if you have a working setup for a headless node or any recommendations

I've written a small guide in my native language and can translate it for you, **but** I used root privileges to install and start Xorg. If you already have Xorg running, then it looks like the root privileges are not required.

**Comment by TopCoder2K** [comment]
> cluster environment restricts Docker usage

I'm afraid that it's not possible to launch the AI2THOR simulator without docker and sudo... But I could be wrong.

> I can try to google translate my way around

The phrases are often too short and too specific, so I decided to translate by myself (commands are in italics): https://disk.yandex.ru/i/A1aX_I9O7r5Zpw
Hope this helps and sorry for the bad look.)) And I hope you do not need a Yandex account to see this (let me know if you do, I'll paste the commands here).

**Comment by gautierdag** [comment]
@TopCoder2K Thank you - I can access it! I'll check it out and update if it works :)
