### ISSUE TITLE
augment_trajectories.py throws error regarding Original Image Count and New Image Count

### ISSUE THREAD

**Issue by jesbu1** [askforalfred/alfred#113]
When cloning the repo from scratch and using either just the json feats or the full dataset, running `augment_trajectories.py` with no changes throws this error for me for all trajectories:

```
Original Image Count 514, New Image Count 0
Traceback (most recent call last):
  File "/home/jesse/alfred/gen/scripts/augment_trajectories.py", line 264, in run
    augment_traj(env, json_file)
  File "/home/jesse/alfred/gen/scripts/augment_trajectories.py", line 244, in augment_traj
    raise Exception("WARNING: the augmented sequence length doesn't match the original")
Exception: WARNING: the augmented sequence length doesn't match the original
Error: Exception("WARNING: the augmented sequence length doesn't match the original")
```

**Comment by MohitShridhar** [comment]
@jesbu1, this is a bit strange. It looks like no new images are being saved. Do you see some agents running around in ai2thor windows? Is anything being saved at all?

**Comment by jesbu1** [comment]
I ended up finding the isseu: what happened is the raw_images are in .jpg and the function that searches for images only looks at .pngs

The images were still saved regardless

**Comment by jesbu1** [comment]
I can make a PR in a bit to fix this bug!
