### ISSUE TITLE
Error in Preprocessing dataset 

### ISSUE THREAD

**Issue by xhding1997** [askforalfred/alfred#139]
Anyone know how to fix it? Thanks !

(alfred) bie@bie:~/alfred$ python models/train/train_seq2seq.py --data data/json_feat_2.1.0 --model seq2seq_im_mask --splits data/splits/oct21.json --gpu --batch 8 --pm_aux_loss_wt 0.1 --subgoal_aux_loss_wt 0.1 --preprocess
Namespace(action_loss_wt=1.0, actor_dropout=0.0, attn_dropout=0.0, batch=8, data='data/json_feat_2.1.0', dataset_fraction=0, dec_teacher_forcing=False, decay_epoch=10, demb=100, dframe=2500, dhid=512, dout='exp/model:seq2seq_im_mask', epoch=20, fast_epoch=False, gpu=True, hstate_dropout=0.3, input_dropout=0.0, lang_dropout=0.0, lr=0.0001, mask_loss_wt=1.0, model='seq2seq_im_mask', pframe=300, pm_aux_loss_wt=0.1, pp_folder='pp', preprocess=True, resume=None, save_every_epoch=False, seed=123, splits='data/splits/oct21.json', subgoal_aux_loss_wt=0.1, temp_no_history=False, use_templated_goals=False, vis_dropout=0.3, zero_goal=False, zero_instr=False)
{'tests_seen': 1533,
 'tests_unseen': 1529,
 'train': 21023,
 'valid_seen': 820,
 'valid_unseen': 821}

Preprocessing dataset and saving to pp folders ... This will take a while. Do this once as required.
Preprocessing tests_seen
Traceback (most recent call last):
  File "models/train/train_seq2seq.py", line 88, in <module>
    dataset.preprocess_splits(splits)
  File "/home/bie/alfred/data/preprocess.py", line 51, in preprocess_splits
    for task in progressbar.progressbar(d):
TypeError: 'module' object is not callable

**Comment by MohitShridhar** [comment]
@xhding1997, related to this https://stackoverflow.com/questions/59294699/progressbar-typeerror-module-object-is-not-callable ?
