### ISSUE TITLE
Error about Socket Exception

### ISSUE THREAD

**Issue by lzr1130** [askforalfred/alfred#146]
When I run the demo to test on ai2thor 2.1.0

c = Controller()
c.start()
event = c.step(dict(action="MoveAhead"))
assert event.frame.shape == (300, 300, 3)
print(event.frame.shape)

there is a socketexception in the player.log:

SocketException: The socket has been shut down
at System.Net.Sockets.Socket.Send (System.Byte[] buf) [0x00000] in :0
at AgentManager+c__Iterator3.MoveNext () [0x00000] in :0
at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in :0

I can see the unity window and see the action of moveahead running, and then it gets stuck.
i use ctrl+c in the command line and see it stops here:

Traceback (most recent call last):
File "/home/orca/anaconda3/envs/alfred210/lib/python3.10/site-packages/ai2thor/controller.py", line 1400, in
event = c.step(dict(action="MoveAhead"))
File "/home/orca/anaconda3/envs/alfred210/lib/python3.10/site-packages/ai2thor/controller.py", line 655, in step
self.last_event = queue_get(self.request_queue)
File "/home/orca/anaconda3/envs/alfred210/lib/python3.10/site-packages/ai2thor/server.py", line 42, in queue_get
res = que.get(block=True, timeout=0.5)
File "/home/orca/anaconda3/envs/alfred210/lib/python3.10/queue.py", line 180, in get
self.not_empty.wait(remaining)
File "/home/orca/anaconda3/envs/alfred210/lib/python3.10/threading.py", line 324, in wait
gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

**Comment by lzr1130** [comment]
Thanks, I have solved that. It's about the version of python. ai2thor doesn't work in python 3.10, it can work in python 3.6.

**Comment by BatmanofZuhandArrgh** [comment]
Hi that's actually what I thought. I'm running 3.9 on ai2thor rn, with the newest alfworld
