### ISSUE TITLE
Evaluation error

### ISSUE THREAD

**Issue by michaal94** [askforalfred/alfred#20]
Hi, I am trying to run an evaluation on the checkpoint you provided. However, I get the following error:
```
Resetting ThorEnv
Process Process-2:
Traceback (most recent call last):
  File "/home/michas/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/michas/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/michas/Desktop/codes/alfred/models/eval/eval_task.py", line 21, in run
    env = ThorEnv()
  File "/home/michas/Desktop/codes/alfred/env/thor_env.py", line 29, in __init__
    super().__init__(quality=quality)
  File "/home/michas/anaconda3/envs/pytorch/lib/python3.7/site-packages/ai2thor/controller.py", line 452, in __init__
    event = self.reset(scene)
  File "/home/michas/Desktop/codes/alfred/env/thor_env.py", line 61, in reset
    super().reset(scene_name)
  File "/home/michas/anaconda3/envs/pytorch/lib/python3.7/site-packages/ai2thor/controller.py", line 484, in reset
    if scene not in self.scenes_in_build:
  File "/home/michas/anaconda3/envs/pytorch/lib/python3.7/site-packages/ai2thor/controller.py", line 474, in scenes_in_build
    event = self.step(action='GetScenesInBuild')
  File "/home/michas/Desktop/codes/alfred/env/thor_env.py", line 139, in step
    if "LookUp" in action['action']:
TypeError: string indices must be integers
```

**Comment by MohitShridhar** [comment]
Hi @michaal94,  

Are you using the correct version of ai2thor, i.e `pip install ai2thor==2.1.0`?

**Comment by MohitShridhar** [comment]
@michaal94, any updates on this? Did the right version of `ai2thor` fix the issue?

**Comment by michaal94** [comment]
Yeah, it helped. Thanks !
