### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by yuweijiang** [askforalfred/alfred#23]
I met a problem with the cuDNN. 
My system is Unbuntu 18.04, my GPU is 2080Ti. I follow the requirement.txt to install the packages.
Could you help me to solve this problem? Thanks a lot!

**Comment by MohitShridhar** [comment]
Hi @yuweijiang can you post the full error? Thanks!

**Comment by yuweijiang** [comment]
Sure, the full error is following.

{'tests_seen': 1533,
 'tests_unseen': 1529,
 'train': 21023,
 'valid_seen': 820,
 'valid_unseen': 821}
Traceback (most recent call last):
  File "models/train/train_seq2seq.py", line 103, in <module>
    model = model.to(torch.device('cuda'))
  File "/home/weijiang.yu/anaconda3/envs/alfred/lib/python3.6/site-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/home/weijiang.yu/anaconda3/envs/alfred/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/weijiang.yu/anaconda3/envs/alfred/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 127, in _apply
    self.flatten_parameters()
  File "/home/weijiang.yu/anaconda3/envs/alfred/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 123, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

**Comment by MohitShridhar** [comment]
@yuweijiang did you follow the installation instructions [here](https://github.com/askforalfred/alfred#quickstart)? 

Also, have you looked at [this](https://discuss.pytorch.org/t/cuda-error-runtimeerror-cudnn-status-execution-failed/17625/5)?
