### ISSUE TITLE
module 'constants' has no attribute 'DETECTION_SCREEN_WIDTH'

### ISSUE THREAD

**Issue by yuweijiang** [askforalfred/alfred#24]
I install the constants=0.6 version. But there is an error as module 'constants' has no attribute 'DETECTION_SCREEN_WIDTH'. Could you help me to solve this problem?

Saving to: exp/model/pm_and_subgoals_01
batch:   0%|                                                                 | 0/2628 [00:00<?, ?it/s]
epoch:   0%|                                                                   | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "models/train/train_seq2seq.py", line 108, in <module>
    model.run_train(splits, optimizer=optimizer)
  File "/home/weijiang/alfred/models/model/seq2seq.py", line 91, in run_train
    for batch, feat in self.iterate(train, args.batch):
  File "/home/weijiang/alfred/models/model/seq2seq.py", line 284, in iterate
    feat = self.featurize(batch)
  File "/home/weijiang/alfred/models/model/seq2seq_im_mask.py", line 127, in featurize
    feat['action_low_mask'].append([self.decompress_mask(a['mask']) for a in ex['num']['action_low'] if a['mask'] is not None])
  File "/home/weijiang/alfred/models/model/seq2seq_im_mask.py", line 127, in <listcomp>
    feat['action_low_mask'].append([self.decompress_mask(a['mask']) for a in ex['num']['action_low'] if a['mask'] is not None])
  File "/home/weijiang/alfred/models/model/seq2seq_im_mask.py", line 176, in decompress_mask
    mask = np.array(decompress_mask(compressed_mask))
  File "/home/weijiang/alfred/gen/utils/image_util.py", line 28, in decompress_mask
    mask = np.zeros((constants.DETECTION_SCREEN_WIDTH, constants.DETECTION_SCREEN_HEIGHT))
AttributeError: module 'constants' has no attribute 'DETECTION_SCREEN_WIDTH'

**Comment by shuyanzhou** [comment]
https://github.com/askforalfred/alfred/blob/master/gen/constants.py#L105

**Comment by MohitShridhar** [comment]
[constants.py](https://github.com/askforalfred/alfred/blob/master/gen/constants.py#L105) is a local file, something seems off with your `PYTHONPATH`.

**Comment by PeterAJansen** [comment]
I had this issue too.  I think the instructions should include the following line: 

export PYTHONPATH="$ALFRED_ROOT/gen/"
