### ISSUE TITLE
ai2thor error in evaluaiton

### ISSUE THREAD

**Issue by sxs4337** [askforalfred/alfred#28]
Run this command on a trained model from a docker image-
```
python3 models/eval/eval_seq2seq.py --model_path model_seq2seq_im_mask_name_pm_and_subgoals_01/best_seen.pth --eval_split valid_seen --data data/json_feat_2.1.0 --model models.model.seq2seq_im_mask --gpu --num_threads 3
```
Get this log-
```
Found path: /root/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64
Mono path[0] = '/root/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Managed'
Mono config path = '/root/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Mono/etc'
Unable to preload the following plugins:
	ScreenSelector.so
Display 0 '0': 5760x1251 (primary device).
Logging to /root/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor/Player.log
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ai2thor/controller.py", line 697, in _start_unity_thread
    raise Exception("command: %s exited with %s" % (command, returncode))
Exception: command: ['/root/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64', '-screen-fullscreen', '0', '-screen-quality', '4', '-screen-width', '300', '-screen-height', '300'] exited with 1
```
Do I need to set some env for running from docker?

**Comment by sxs4337** [comment]
Fixed by setting the correct X variable- https://github.com/askforalfred/alfred/blob/master/gen/constants.py#L88
My system needed variable 1. Setting DISPLAY to 0 did not help.

**Comment by MohitShridhar** [comment]
Thanks! Will update the Docker guide soon.
