### ISSUE TITLE
Run with docker_enabled=True

### ISSUE THREAD

**Issue by shuyanzhou** [askforalfred/alfred#3]
Hi,

It seems the env.last_event.IMAGE_RELATED_ATTRIBUTES (e.g. frame) are None with docker_enabled=True. I am using the Dockerfile from ai2thor repo. I also tried the following code, the results are the same:
```python
import ai2thor.controller
controller = ai2thor.controller.Controller()
controller.docker_enabled = True
controller.start()
# can be any one of the scenes FloorPlan###
controller.reset('FloorPlan28')
controller.step(dict(action='Initialize', gridSize=0.25))
controller.step(dict(action='RotateRight'))
controller.last_event.frame == None # True
```
I notice there is a TODO docker session in the README file and I was wondering how could I evaluate the model with docker? 

Thanks.

**Comment by shuyanzhou** [comment]
Hi,

I am trying to build a new image (mostly) from scratch. I am using pytorch/pytorch:1.1.0-cuda10.0-cudnn7.5-devel from pytorch’s docker hub. 

* ssh to the server with x11 forwarding to my local machine 
```bash
ssh -X MY_LINUX_MACHINE
```

* docker run interactively and install xserver related packages based on ai2thor’s dockerfile
```bash
apt-get -qq update && apt-get -qqy upgrade
apt-get -qqy install xserver-xorg-core xserver-xorg-video-dummy libxcursor1 x11vnc unzip pciutils software-properties-common kmod gcc make linux-headers-generic wget
```
* container commit and log into the container again
```bash
docker run -it -v path_to_code_and_data:/root/ -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /tmp/  --net=host --runtime=nvidia --shm-size 8G  alfred:1.1.0-cuda10.0-cudnn7.5-devel
```
* forwarding display to linux server (then to my local machine)
```bash
xac ${container_id}
```
```xterm``` and ```glxgears`` on the docker could correctly appear in my local machine. However, I get an error when running the 
```python
import ai2thor.controller
controller = ai2thor.controller.Controller()
controller.start()
```

> Found path: /root/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64
Mono path[0] = '/root/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Managed’
Mono config path = '/root/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Mono/etc’
Unable to preload the following plugins:
	ScreenSelector.so
Display 0 'default': 3360x1058 (primary device).
Logging to /root/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor/Player.log
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.6/site-packages/ai2thor/controller.py", line 697, in _start_unity_thread
    raise Exception("command: %s exited with %s" % (command, returncode))
Exception: command: ['/root/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64', '-screen-fullscreen', '0', '-screen-quality', '7', '-screen-width', '300', '-screen-height', '300'] exited with 1

Docker OS:
> NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

Server OS:
>NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
