### ISSUE TITLE
Evaluation Error, "Directory Not Empty"

### ISSUE THREAD

**Issue by yukiTakezawa** [askforalfred/alfred#43]
Hello, my environment is 
* Ubuntu 20.04
* GTX 1060

I downloaded the pre-train model and to evaluate it I set up a docker environment.
When I run the following command after I run script/run_docker.py, Error occurred.

```
(alfred_env) yuki@yuki-lab:~/alfred$ python models/eval/eval_seq2seq.py --model_path baseline/best_seen.pth --eval_split valid_seen --data data/json_feat_2.1.0 --model models.model.seq2seq_im_mask --gpu --num_threads 3
{'tests_seen': 1533,
 'tests_unseen': 1529,
 'train': 21023,
 'valid_seen': 820,
 'valid_unseen': 821}
Loading:  baseline/best_seen.pth
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /home/yuki/.cache/torch/checkpoints/resnet18-5c106cde.pth
100%|######################################################################################################################################################| 46827520/46827520 [00:04<00:00, 11243319.04it/s]
thor-201909061227-Linux64: [||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%   4.3 MiB/s]  of 390.MB
thor-201909061227-Linux64: [||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||                                               70%   3.0 MiB/s]  of 390.MBNo protocol specified
Found path: /home/yuki/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64
Mono path[0] = '/home/yuki/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Managed'
Mono config path = '/home/yuki/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Mono/etc'
thor-201909061227-Linux64: [|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||                                          72%   2.9 MiB/s]  of 390.MBPreloaded 'ScreenSelector.so'
PlayerPrefs - Creating folder: /home/yuki/.config/unity3d/Allen Institute for Artificial Intelligence
PlayerPrefs - Creating folder: /home/yuki/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor
Logging to /home/yuki/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor/Player.log
No protocol specified
thor-201909061227-Linux64: [||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%   3.4 MiB/s]  of 390.MB
thor-201909061227-Linux64: [||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%   3.3 MiB/s]  of 390.MB
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuki/alfred/models/eval/eval_task.py", line 20, in run
    env = ThorEnv()
  File "/home/yuki/alfred/env/thor_env.py", line 33, in __init__
    player_screen_width=player_screen_width)
  File "/home/yuki/alfred_env/lib/python3.5/site-packages/ai2thor/controller.py", line 858, in start
    self.download_binary()
  File "/home/yuki/alfred_env/lib/python3.5/site-packages/ai2thor/controller.py", line 796, in download_binary
    os.rename(extract_dir, os.path.join(self.releases_dir(), self.build_name()))
OSError: [Errno 39] Directory not empty: '/home/yuki/.ai2thor/tmp/thor-201909061227-Linux64' -> '/home/yuki/.ai2thor/releases/thor-201909061227-Linux64'
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yuki/alfred/models/eval/eval_task.py", line 20, in run
    env = ThorEnv()
  File "/home/yuki/alfred/env/thor_env.py", line 33, in __init__
    player_screen_width=player_screen_width)
  File "/home/yuki/alfred_env/lib/python3.5/site-packages/ai2thor/controller.py", line 858, in start
    self.download_binary()
  File "/home/yuki/alfred_env/lib/python3.5/site-packages/ai2thor/controller.py", line 796, in download_binary
    os.rename(extract_dir, os.path.join(self.releases_dir(), self.build_name()))
OSError: [Errno 39] Directory not empty: '/home/yuki/.ai2thor/tmp/thor-201909061227-Linux64' -> '/home/yuki/.ai2thor/releases/thor-201909061227-Linux64'
```
And I set num_threads 1, then eval_seq2seq.py print "No Protocol Specified".

```
yuki@yuki-lab:~/alfred$ python models/eval/eval_seq2seq.py --model_path <model_path>/best_seen.pth --eval_split valid_seen --data data/json_feat_2.1.0 --model models.model.seq2seq_im_mask --gpu --num_threads 3 --subgoals all^C
yuki@yuki-lab:~/alfred$ python models/eval/eval_seq2seq.py --model_path baseline/best_seen.pth --eval_split valid_seen --data data/json_feat_2.1.0 --model models.model.seq2seq_im_mask --gpu --num_threads 1 
{'tests_seen': 1533,
 'tests_unseen': 1529,
 'train': 21023,
 'valid_seen': 820,
 'valid_unseen': 821}
Loading:  baseline/best_seen.pth
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /home/yuki/.cache/torch/checkpoints/resnet18-5c106cde.pth
100%|######################################################################################################################################################| 46827520/46827520 [00:04<00:00, 11261491.30it/s]
thor-201909061227-Linux64: [||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%   7.6 MiB/s]  of 390.MB
No protocol specified
Found path: /home/yuki/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64
Mono path[0] = '/home/yuki/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Managed'
Mono config path = '/home/yuki/.ai2thor/releases/thor-201909061227-Linux64/thor-201909061227-Linux64_Data/Mono/etc'
Preloaded 'ScreenSelector.so'
PlayerPrefs - Creating folder: /home/yuki/.config/unity3d/Allen Institute for Artificial Intelligence
PlayerPrefs - Creating folder: /home/yuki/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor
Logging to /home/yuki/.config/unity3d/Allen Institute for Artificial Intelligence/AI2-Thor/Player.log
No protocol specified

```
 Is this message correct?
And can I deal with the first problem?

Thank you.

**Comment by MohitShridhar** [comment]
@yukiTakezawa are you running this on a headless machine without a display? If so, have you followed [this guide](https://github.com/askforalfred/alfred#cloud-instance)?

**Comment by yukiTakezawa** [comment]
My PC is not a headless machine, but I run eval_seq2seq.py on docker.
Do I need to run strartx.py?

**Comment by MohitShridhar** [comment]
No, for a local machine with a display it should be fine. But can you run `glxgears` inside the container without any issues? Do you see spinning gears?

It seems like it's something [related to X](https://stackoverflow.com/questions/48833451/no-protocol-specified-when-running-a-sudo-su-app-on-ubuntu-linux).

**Comment by yukiTakezawa** [comment]
When I run `glxgears`, I can see spinning gears.

**Comment by MohitShridhar** [comment]
Is your `DISPLAY` environment variable pointing the right display? `:0` or something else?

**Comment by yukiTakezawa** [comment]
On my PC `echo $DISPLAY` is 1.
And  in `script/run_docker.py`, `-e DISPLAY -e QT_X11_NO_MITSHM=1 -v /tmp/.X11-unix:/tmp/.X11-unix:rw`.
Is this the problem?

**Comment by yukiTakezawa** [comment]
In addition,  I run `xhost +` on my PC (not docker), but `eval_seq2seq.py` still print "No Protocol Specified" on docker.
And I can run `glxgears` on docker without any issues too.

**Comment by yukiTakezawa** [comment]
https://github.com/askforalfred/alfred/issues/28 is very useful for this issue.
I change `X_DISPLAY = '0'` in `gen/constants.py` to `X_DISPLAY = '1'`, because `$DISPLAY` on my PC and docker is 1.
And `eval_seq2seq.py` began to work successfully.
Thank you very much!
