### ISSUE TITLE
Error when running evaluation: TypeError: string indices must be integers

### ISSUE THREAD

**Issue by soyeonm** [askforalfred/alfred#65]
Hello, when I run the following command:

`python3.8 models/eval/eval_seq2seq.py --model_path models/pre-trained_models/best_seen.pth --eval_split valid_seen --data data/json_2.1.0 --model models.model.seq2seq_im_mask  --num_threads 1 `

I get the following error:

> {'tests_seen': 1533,
>  'tests_unseen': 1529,
>  'train': 21023,
>  'valid_seen': 820,
>  'valid_unseen': 821}
> Loading:  models/pre-trained_models/best_seen.pth
> Resetting ThorEnv
> Process Process-2:
> Traceback (most recent call last):
>   File "/Users/soyeonmin/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/Users/soyeonmin/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/Volumes/Transcend/alfred/models/eval/eval_task.py", line 20, in run
>     env = ThorEnv()
>   File "/Volumes/Transcend/alfred/env/thor_env.py", line 29, in __init__
>     super().__init__(quality=quality)
>   File "/Users/soyeonmin/opt/anaconda3/lib/python3.8/site-packages/ai2thor/controller.py", line 454, in __init__
>     event = self.reset(scene)
>   File "/Volumes/Transcend/alfred/env/thor_env.py", line 61, in reset
>     super().reset(scene_name)
>   File "/Users/soyeonmin/opt/anaconda3/lib/python3.8/site-packages/ai2thor/controller.py", line 509, in reset
>     if scene not in self.scenes_in_build:
>   File "/Users/soyeonmin/opt/anaconda3/lib/python3.8/site-packages/ai2thor/controller.py", line 499, in scenes_in_build
>     event = self.step(action='GetScenesInBuild')
>   File "/Volumes/Transcend/alfred/env/thor_env.py", line 139, in step
>     if "LookUp" in action['action']:
> TypeError: string indices must be integers

What is 'action' supposed to be? Is it supposed to be a string like 'GetScenesInBuild'? It seems that  'GetScenesInBuild' from ai2thor and your _thor_env.py_  are inconsistent. How can I avoid this problem? Thanks.

**Comment by soyeonm** [comment]
No worries, I resolved it by finding an existing closed issue!
